version: "3.0"
services:
  proxy:
    build: ./docker/proxy/
    image: mcleonte/zaida-proxy
    container_name: zaida-proxy
    ports:
      - ${PUBLIC_PORT}:${PUBLIC_PORT}
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/
      - PORT_1
      - PUBLIC_PORT
    depends_on:
      - wshub

  wshub:
    build: ./docker/wshub/
    image: mcleonte/zaida-wshub
    container_name: zaida-wshub
    volumes:
      - ./docker/wshub/:/usr/src/app/
    expose:
      - ${PORT_1}
    environment:
      - PORT_1
      - LOG_LEVEL

  stt:
    build:
      context: ./docker/stt/
      dockerfile: ${DEVICE}.Dockerfile
    image: mcleonte/zaida-stt
    container_name: zaida-stt
    volumes:
      - ./docker/stt/:/app/
    environment:
      - NLU_URI=http://nlu:${NLU_PORT}/webhooks/callback/webhook
      - WSHUB_URI
      - LOG_LEVEL
      - ZAIDA_USER
      - MODEL_PATH=/app/models
      - MODEL_NAME=small.en
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: 1
    depends_on:
      nlu:
        condition: service_healthy
      - wshub

  tts:
    build:
      context: ./docker/tts
      dockerfile: ${DEVICE}.Dockerfile
    image: mcleonte/zaida-tts
    container_name: zaida-tts
    volumes:
      - ./docker/tts/:/app/
      - mimic3_voices:/home/mimic3/.local/share/mycroft/mimic3/voices/
    environment:
      - WSHUB_URI
      - PORT_1
      - LOG_LEVEL
      - VOICE=en_US/vctk_low#p240
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: 1
    depends_on:
      - wshub

  nlu:
    build: ./docker/nlu/
    image: mcleonte/zaida-nlu
    container_name: zaida-nlu
    user: 1000:1000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nlu:${NLU_PORT}"]
      interval: 7s
      retries: 10
    expose:
      - ${NLU_PORT}
    volumes:
      - ./docker/nlu:/app
      - spacy_models:/opt/venv/lib/python3.10/site-packages/en_core_web_lg
    command: run --debug --port ${NLU_PORT}
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - TTS_NLU_PORT
      - ACTIONS_PORT
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: 1

  actions:
    build:
      context: ./docker/actions/
      dockerfile: ${DEVICE}.Dockerfile
    image: mcleonte/zaida-actions
    container_name: zaida-actions
    expose:
      - ${ACTIONS_PORT}
    volumes:
      - ./docker/actions/actions:/app/actions
      - actions_cache:/app/.cache/
      - /etc/localtime:/etc/localtime
    command: --port ${ACTIONS_PORT}
    environment:
      - XDG_CACHE_HOME=/app/.cache/
      - LOG_LEVEL
      - DEVICE
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: 1


volumes:
  actions_cache:
  mimic3_voices:
  spacy_models:
